### ISSUE TITLE
New container for each test

### ISSUE THREAD

**Issue by hrach** [nette/bootstrap#35]
Due to this change https://github.com/nette/bootstrap/commit/549fae02376e43a20d45a0482bc470475ba90ffb a new Container is generated for each test file. Cointaner has different parameters -> different caching key.

**Comment by dg** [comment]
Is it issue?

**Comment by fprochazka** [comment]
Kind of. I certainly don't wanna generate new container for the same configuration, when it's compilation takes about 10 seconds.

**Comment by fprochazka** [comment]
Kind of. I certainly don't wanna generate new container for the same configuration, when it's compilation takes about 10 seconds. Fortunately, I'm setting the parameter manually, so I don't really care if this issue is resolved. Being it up to me I'd close it because there exists reasonable workaround.

**Comment by hrach** [comment]
Dunno what is it good for. The point that there is workaround make this less important, but do not close the issue.

**Comment by fprochazka** [comment]
The problem is that the dir is autodetected and you really have no way of reliable autodetection of this stuff from tests directory.

**Comment by fprochazka** [comment]
#61 might solve this
